---
title: "Aula 11"
description: "Habeas corpus"
author:
  - name: Luccas Gissoni
    affiliation: Universidade Zumbi dos Palmares
    affiliation_url: https://zumbidospalmares.edu.br/
date: "`r Sys.Date()`"
bibliography: pco.bib
csl: abnt.csl
output: 
---

# Introdução

> Os remédios constitucionais são processos regulamentados pela
> Constituição que objetivam reparar judicialmente danos e/ou afastar
> impedimentos no exercício de direitos fundamentais causados por
> decisões estatais com vício jurídico [@dimoulis_curso_2016 p. 399].

Há 4 critérios para "incluir um remédio no processo constitucional no
sentido amplo\" [@dimoulis_curso_2016 p. 399]:

1.  Sua regulamentação -- ainda que rudimentar -- pela Constituição;

2.  O fato de o Estado ser causador da lesão;

3.  A finalidade de tutelar direitos fundamentais;

4.  Deve se tratar de remédio de competência judicial (excluindo os
    extrajudiciais).

> Mesmo não sendo exclusivamente dedicados ao controle de
> constitucionalidade, os remédios constitucionais são analisados aqui
> por duas razões. Do ponto de vista didático, fazem tradicionalmente
> parte do estudo do processo constitucional, porque se relacionam com a
> tutela dos direitos fundamentais. Já do ponto de vista teórico, fazem
> parte do processo constitucional no sentido amplo, porque fiscalizam a
> regularidade normativa de atos estatais tutelando direitos
> constitucionais.\
> Do ponto de vista processual, apesar de serem comuns as denominações
> "remédios", "recursos", "garantias" ou "*writs*" (adotando o termo
> inglês), trata-se de ações. Suas características são estudadas em
> seguida.\
> Do ponto de vista constitucional, essas ações objetivam garantir
> direitos fundamentais de determinados titulares. Por essa razão, ainda
> que a ação tenha caráter coletivo, configura "garantia individual",
> protegida como cláusula pétrea pelo art. 60, § 4o, IV, da Constituição
> Federal[^1] [@dimoulis_curso_2016 p. 399].

# *Habeas corpus*

O habeas corpus é uma ação constitucional de rito especial destinada a proteger o direito à liberdade de locomoção contra ilegalidade ou abuso de poder.

# Previsão Legal

- **Constituição Federal**, art. 5º, LXVIII.
- **Código de Processo Penal**, arts. 647 a 667.

# Cabimento

> O habeas corpus poderá ser impetrado quando alguém sofrer restrição ilegal quanto a sua liberdade de locomoção ou a ameaça [@barroso_pratica_2024, p. 21].

O habeas corpus é cabível:

- **Repressivo**: quando a ilegalidade já ocorreu.
- **Preventivo**: quando há a ameaça de restrição à liberdade.

⚠️ **Atenção**: Não se admite habeas corpus contra a discricionariedade da aplicação de prisão disciplinar a militares, salvo por ilegalidade.

# Legitimidade

## Legitimidade ativa

- Qualquer pessoa pode impetrar.
- Pode ser impetrado por terceiro em favor do paciente.

## Legitimidade passiva

- A autoridade ou particular responsável pela ilegalidade ou ameaça.

# Liminar

- Possibilidade de concessão de liminar mediante:
  - **Fumus boni iuris**: fundamentação relevante.
  - **Periculum in mora**: risco de ineficácia da decisão.

# Competência

A competência é definida pela autoridade coatora/paciente e será descoberta pela análise dos seguintes itens:

- **a)** Categoria da autoridade coatora – competência originária de Tribunal (foro por prerrogativa de função);
- **b)** Categoria do paciente – competência originária de Tribunal (foro por prerrogativa de função);
- **c)** Sede funcional – as demais autoridades públicas que não possuem foro por prerrogativa de função para habeas corpus serão julgadas em primeiro grau.

> Se a autoridade estiver vinculada a Estados, Municípios ou Distrito Federal, a competência será da justiça estadual ou do Distrito Federal e Territórios; se a autoridade for federal, a competência será da justiça federal [@barroso_pratica_2024, p. 22].

## Competência por autoridade coatora

| Órgão competente | Autoridade coatora |
|:------------------|:-------------------|
| Superior Tribunal Federal (art. 102, I, i da CF) | - Tribunal Superior<br>- Presidente da República<br>- Mesa da Câmara dos Deputados<br>- Mesa do Senado Federal<br>- Tribunal de Contas da União<br>- Procurador-Geral da República<br>- Supremo Tribunal Federal<br>- Conselho Nacional de Justiça<br>- Conselho Nacional do Ministério Público |
| Superior Tribunal de Justiça (art. 105, I, c da CF) | - Governadores<br>- Desembargadores<br>- Membros dos Tribunais de Contas dos Estados e Municípios<br>- Membros do Ministério Público da União<br>- Ministros de Estado<br>- Comandantes da Marinha, do Exército e da Aeronáutica |
| Tribunal de Justiça / Tribunal Regional Federal | - Juiz de direito (estadual) / Juiz federal |
| Primeira instância da justiça estadual ou federal | - Demais autoridades públicas ou a elas equiparadas |

## Competência por paciente

| Pacientes | Órgão competente |
|:---------|:------------------|
| - Presidente da República<br>- Vice-Presidente da República<br>- Membros do Congresso Nacional<br>- Ministros do Supremo Tribunal Federal<br>- Procurador-Geral da República<br>- Ministros de Estado<br>- Comandantes das Forças Armadas<br>- Membros do Tribunal de Contas da União<br>- Chefes de Missões Diplomáticas Permanentes | Superior Tribunal Federal |


# Pedidos no Habeas Corpus

- Notificação da autoridade coatora.
- Intimação do Ministério Público.
- Procedência para garantir a liberdade do paciente.
- Juntada de provas documentais.

# Modelo de Peça: Habeas Corpus

<div style="background-color:#f7f7f7; border-left: solid 4px #cccccc; padding: 1em; font-family: monospace;">

EXCELENTÍSSIMO SENHOR DOUTOR JUIZ DE DIREITO DA ... VARA

CÍVEL/FAZENDA PÚBLICA DA COMARCA DE ..., ESTADO ...

NOME DO IMPETRANTE, nacionalidade ..., estado civil ..., profissão ..., inscrito no CPF sob o n. ..., residente e domiciliado na ..., endereço eletrônico ..., por meio de seu advogado, que esta subscreve (instrumento de mandato incluso), com escritório na ..., endereço eletrônico ..., NOME DO PACIENTE, nacionalidade ..., estado civil ..., profissão ..., inscrito no CPF sob o n. ..., residente e domiciliado na ..., vem respeitosamente à presença de Vossa Excelência, com fundamento no art. 5º, LXVIII, da Constituição Federal, impetrar o presente

"HABEAS CORPUS"

COM PEDIDO DE LIMINAR

contra NOME DO IMPETRADO, nacionalidade ..., estado civil ..., profissão ..., inscrito no CPF sob o n. ..., residente e domiciliado na ..., pelos motivos de fato e de direito a seguir aduzidos.

I – DO CABIMENTO

1. Pertinência do objeto

Demonstrar que o objeto (violação à liberdade de locomoção) pode ser tratado em "habeas corpus", conforme o art. 5º, LXVIII, da Constituição Federal.

2. Legitimidade

2.1. Legitimidade ativa

Demonstrar a legitimidade da impetrante e paciente.

2.2. Legitimidade passiva

Demonstrar que o impetrado é o responsável pelo ato ou ameaça de violação à liberdade de locomoção.

II – DOS FATOS

Apresentar a síntese dos fatos apresentados no enunciado.

III – DO DIREITO

Apresentar as teses jurídicas aplicáveis ao caso.

(Seguir lógica argumentativa: violação a princípios → fundamentos constitucionais → fundamentos infraconstitucionais → fundamentos jurisprudenciais e doutrinários)

IV – DA LIMINAR

A ação do habeas corpus admite decisão liminar desde que preenchidos dois requisitos:

a) fundamento relevante (fumus boni iuris);
b) risco de ineficácia do provimento (periculum in mora).

V – DOS PEDIDOS

Ante o exposto, requer:

a) a notificação do coator para apresentar informações;
b) a intimação do Ministério Público para manifestação;
c) a procedência do pedido para a liberdade do paciente;
d) a juntada da prova documental quanto à violação da liberdade de locomoção.

Termos em que pede deferimento.

Local e data.

ADVOGADO...

OAB...

</div>