---
title: "Progama da disciplina"
description: |
  1º semestre 2025
output: distill::distill_article
bibliography: PCO.bib
csl: abnt.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Semana 1

[**Notas de aula**](notas_1.html)  
**Bibliografia:** @dimoulis_curso_2016, cap. 1

### 15.08.25 - aula 1.1: introdução

  1. Apresentação do curso
  1. Leitura do programa
  1. O conceito de processo
      a. O processo como abstração de segunda ordem
      a. Estudo de comportamento x estudo de regras

## Semana 2

[**Notas de aula**](notas_2.html)  
**Bibliografia:** @dimoulis_curso_2016, cap. 1

### 18.08.25 - aula 2.1: processo legal e processo judicial

  1. Processo legal
  1. Processo judicial
      a. Características das decisões judiciais
      a. Sanções
      a. O processo judicial e a pacificação de conflitos
  1. Processo constitucional: definições
      a. Definição restrita
      a. Definição média
      a. Definição ampla
  1. O estudo do processo constitucional

### 22.08.25 - aula 2.2: direito processual

  1. Normas processuais civis
      a. Eficácia da norma processual
      a. Interpretação da norma processual
  1. Função jurisdicional
      a. Jurisdição
      a. Ação
      a. Competência

## Semana 3

[**Notas de aula**](notas_3.html)  
**Bibliografia:** @dimoulis_curso_2016, cap. 1

### 25.08.25 - aula 3.2: a supremacia da constituição e o controle de constitucionalidade

  1. Definição
      a. Conteúdo
      a. Forma
      a. Razão
  1. Quem deve garantir a supremacia da constituição?
      a. O Poder Legislativo
      a. O Poder Executivo
      a. O Poder Judiciário
          i. Controle difuso de constitucionalidade
          i. Controle concentrado de constitucionalidade

### 29.08.25 - PAP 1.1
          
[**PAP 1.1:** Marbury vs. Madison e a emergência do controle de constitucionalidade](pap_11.html)  
**Prazo:** 05/03

## Semana 4

### 01.09.25 - aula 4.1: inconstitucionalidade e controle de constitucionalidade

[**Notas de aula**](notas_4.html)  
**Bibliografia:** @dimoulis_curso_2016, cap. 1

  1. Modelos de controle de constitucionalidade
      a. Quanto ao npumero de fiscais da constitucionalidade
          i. Sistema difuso (universal)
          i. Sistema concentrado
          i. Sistemas mistos?
      a. Quanto ao tipo de fiscalização
          i. Concreto
          i. Abstrato
  1. Formas de inconstitucionalidade
      a. Quanto à natureza da norma violada
          i. Inconstitucionalidade formal
          i. Inconstitucionalidade material
      a. Quanto ao momento de ocorrência da inconstitucionalidade
          i. Inconstitucionalidade originária
          i. Inconstitucionalidade superveniente
      

### 05.09.25 - aula 4.2: processo constitucional

[**Notas de aula**](notas_4_extra.html)  
**Bibliografia:** @brasil_constituicao_1988; @mendes_curso_2024; @moraes_direito_2023 

  1. Iniciativa
      a. Iniciativa comum
      a. Iniciativa reservada
          i. Iniciativa reservada ao Judiciário
          i. Iniciativa reservada ao Ministério Público
          i. Iniciativa reservada ao Legislativo
          i. Iniciativa reservada ao Executivo
  1. Discussão
  1. Votação
  1. Sanção e veto
  1. Promulgação e publicação
  
## Semana acadêmica

### 08.09.25 - aula 4.1: inconstitucionalidade e controle de constitucionalidade

### 12.09.25 - aula 4.1: inconstitucionalidade e controle de constitucionalidade

## Semana 5

[**Notas de aula**](notas_5.html)  
**Bibliografia:** @barroso_pratica_2024, pp. 128-160

### 15.09.25 - aula 5.1: ação direta de inconstitucionalidade e ação direta de inconstitucionalidade por omissão

### 19.09.25 - aula 5.2: ação direta de inconstitucionalidade e ação direta de inconstitucionalidade por omissão

[**PAP 1.2:** ADIn - oficina de peça profissional](pap_12.html)  
**Prazo:** 23/03

## Semana 6

[**Notas de aula**](notas_6.html)  
**Bibliografia:** @barroso_pratica_2024, pp. 149-172

### 22.09.25 - aula 6.1: ação declaratória de constitucionalidade

### 26.09.25 - aula 6.2: ação declaratória de constitucionalidade

[**PAP 1.3:** ADC - oficina de peça profissional](pap_13.html)  
**Prazo:** 06/04

## Semana 7

### 29.09.25

### 03.10.25 - PAT-1

## Semana 8

**Bibliografia:** @barroso_pratica_2024, pp. 183-194

### 06.10.25 - aula 8.1: arguição de Descumprimento de Preceito Fundamental

### 10.10.25 - aula 8.2: arguição de Descumprimento de Preceito Fundamental

[**PAP 1.4:** ADPF - oficina de peça profissional](pap_14.html)  
**Prazo:** 16/04

## Semana 9

[**Notas de aula**](notas_9.html)  
**Bibliografia:** @dimoulis_curso_2016, cap. 5

### 13.10.25 - aula 9.1: correção da PAT-1

### 17.10.25 - aula 9.2: métodos de interpretação constitucional
  
  1.  Introdução  
  1.  Métodos clássicos de interpretação  
      a.  Interpretação textual (ou gramatical)
      a.  Interpretação sistemática
      a.  Interpretação histórica (teleologia subjetiva)
      a.  Interpretação teleológica objetiva
  1.  Problemas dos métodos interpretativos  
  1.  Técnicas decisórias no controle de constitucionalidade  
      a.  Interpretação conforme a Constituição
      a.  Inconstitucionalidade parcial sem redução de texto
      a.  Decisões manipulativas
      a.  Apelo ao legislador
  1.  Mutação constitucional  
      a.  Caso emblemático: Reclamação 4.335
  1.  Considerações finais 

**PAP 2.1:** RC - oficina de peça profissional

## Semana 10

[**Notas de aula**](notas_10.html) 
**Bibliografia:** @barroso_pratica_2024, pp. 195-207

### 20.10.25

### 24.10.25 - aula 10.1: reclamação constitucional e súmula vinculante

[**PAP 2.1:** RC - oficina de peça profissional](pap_21.html)  
**Prazo:** 27/04

## Semana 11

[**Notas de aula**](notas_11.html)  
**Bibliografia:** @barroso_pratica_2024, pp. 21-30

### 27.10.25 - aula 11.1: *habeas corpus*

### 31.10.25 - aula 11.2: *habeas corpus*

[**PAP 2.2:** HC - oficina de peça profissional](pap_22.html)  
**Prazo:** 04/05

## Semana 12

[**Notas de aula**](notas_12.html)  
**Bibliografia:** @barroso_pratica_2024, pp. 61-88

### 03.11.25 - aula 12.1: mandado de segurança individual

### 07.11.25 - aula 12.2: mandado de segurança coletivo

[**PAP 2.3:** MS - oficina de peça profissional](pap_23.html)  
**Prazo:** 11/05

## Semana 13

### 10.11.25

### 14.11.25

## Semana institucional

### 17.11.25 - **atividades institucionais**

### 21.11.25 - **Emenda Feriado Consciência Negra**

## Semana 14

[**Notas de aula**](notas_14.html)  
**Bibliografia:** @barroso_pratica_2024, pp. 89-105

### 24.11.25 - aula 14: ação popular

[**PAP 2.4:** AP - oficina de peça profissional](pap24.html)  
**Prazo:** 01/06

### 28.11.25 - **Dia de avaliação PAT2**

## Semana de avaliação

### 01.12.25 - Sem aula – Já finalizou o conteúdo

### 05.12.25 - **Dia de avaliação SUBS**

## Semana de avaliação

### 08.12.25 - Sem aula – Já finalizou o conteúdo

### 12.12.25 - **Dia de avaliação de EXAME**

## Semana de revisão de notas

### 15.12.25 - Sem aula – Já finalizou o conteúdo

### 19.12.25 - **Revisão de notas e faltas**